import ThemeProv from "./comps/themeprov";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProv>
        <body>{children}</body>
      </ThemeProv>
    </html>
  );
}
